controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - torch_tip
  - name: fake_wrist_controller
    type: $(arg fake_execution_type)
    joints:
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_armNoTool_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home